name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest -v
